# .github/workflows/release.yml
name: Release Go Project

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Prepare Release Notes
        run: |
          # Copy the template to a new file that GoReleaser will use
          cp README.template.md .github/release_notes.md

      - name: Update Version in Release Notes
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "__VERSION__"
          replace: "${{ github.ref_name }}"
          include: ".github/release_notes.md"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          # GoReleaser will automatically pick up the .github/release_notes.md file
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}