# .github/workflows/release.yml
name: Release Go Project

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is still needed
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # We need to fetch all history for changelog generation
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # --- NEW STEP 1: Find and Replace Version ---
      # This step finds __VERSION__ in your README.md and replaces it
      # with the Git tag name (e.g., v0.1.0).
      - name: Update docs version
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "__VERSION__"
          replace: "${{ github.ref_name }}"
          include: "README.md" # You can add more files, e.g., "README.md,docs/usage.md"

      # --- NEW STEP 2: Commit and Push Changes ---
      # This step commits the modified README.md back to your main branch.
      - name: Commit updated docs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Update version to ${{ github.ref_name }}"
          commit_options: '--no-verify'
          file_pattern: 'README.md' # Make sure this matches the files you changed
          
      # --- EXISTING STEP: Run GoReleaser ---
      # This runs last, after the docs have been updated and committed.
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}